ConnectionStrings: 
    MicroservicesClientConnectionString: Data Source=.;Initial Catalog=LibraryMSARelease;Persist Security Info=True;User ID=galaxy;Password=Password123  
JwtSettings: 
    Audience: Microservices.ConfigServer.ClientRelease